/** Canonical paths — use everywhere nav/footer link */
export const ROUTES = {
  home: "/",
  homeMembership: "/#membership",
  homeProtocols: "/#protocols",
  homeFaq: "/#faq",
  glpOne: "/glp-one",
  glpOneFaq: "/glp-one#faq",
  signup: "/signup",
  about: "/about",
  aboutVitality: "/about/vitality",
  aboutHowItWorks: "/about/how-it-works",
  learn: "/learn",
  learnFeatured: "/learn/meet-your-metabolism",
  learnWhatToExpect: "/learn/what-to-expect",
  learnProtocolAreas: "/learn/protocol-areas",
  learnUniqueGoals: "/learn/as-unique-as-your-goals",
  learnWhatWeMeasure: "/learn/what-we-measure",
  learnOurProgram: "/learn/our-program",
  contact: "/contact",
  faq: "/faq",
  connect: "/connect",
  terms: "/terms",
  termsRefunds: "/terms#refunds",
  privacy: "/privacy",
  accessibility: "/accessibility",
  homeHowItWorks: "/#how-it-works",
} as const;
