/** Canonical paths — use everywhere nav/footer link */
export const ROUTES = {
  home: "/",
  homeFaq: "/#faq",
  homeHowItWorks: "/#how-it-works",
  pricing: "/pricing",
  pricingFaq: "/pricing#pricing-faq",
  about: "/about",
  treatmentsLean: "/treatments/lean",
  treatmentsRegulation: "/treatments/regulation",
  treatmentsVitality: "/treatments/vitality",
  learn: "/learn",
  learnFeatured: "/learn/meet-your-metabolism",
  learnWhatToExpect: "/learn/what-to-expect",
  learnProtocolAreas: "/learn/protocol-areas",
  learnUniqueGoals: "/learn/as-unique-as-your-goals",
  learnWhatWeMeasure: "/learn/what-we-measure",
  learnOurProgram: "/learn/our-program",
  contact: "/contact",
  terms: "/terms",
  termsRefunds: "/terms#refunds",
  privacy: "/privacy",
  accessibility: "/accessibility",
} as const;
